@startuml DataObject

legend top left
    Project
        BI_CSHARP_GCP

    Diagram
        CreateObject sequence [DataObject]

    Authors
        Armand MARECHAL
        Mauro COSTA-DOS-SANTOS 
endlegend

package GCP_Microservice {
    interface IDataObject {
     +doesExist(string key) : boolean
     +create(string key, string path, bool? force) : void
     +download(string key) : byte[]
     +publish(string key) : string
    }

    class GCPDataObject {
     -client : StorageClient
     -bucket : String
    }

    class DataObjectAlreadyExistsException {
     +dataObjectAlreadyExistsException(message : string)
    }

    class DataObjectNotFoundException {
     +dataObjectNotFoundException(message : string)
    }
}

package GCP_SDK {}

IDataObject <|.. GCPDataObject
GCP_Microservice ..> GCP_SDK: Imports

class Exception

GCPDataObject ..> DataObjectAlreadyExistsException : throws
GCPDataObject ..> DataObjectNotFoundException : throws

DataObjectAlreadyExistsException --|> Exception
DataObjectNotFoundException --|> Exception

@enduml
