name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Export secrets as environment variables
      run: |
        touch .env
        echo "GCP_BUCKET=${{ secrets.GCP_BUCKET }}" >> .env
        echo "GCP_TOKEN=${{ secrets.GCP_TOKEN }}" >> .env

    - name: Export secrets as environment variables
      run: echo "${{ secrets.GCP_BUCKET }}"

    - name: Print .env file
      run: cat .env

    - name: Create .env file
      run: | 
        touch TestGCPMicroservice/.env
        touch GCPMicroservice/.env
        cp .env TestGCPMicroservice/.env
        cp .env GCPMicroservice/.env
      
    - name: Print TestGCPMicroservice .env file
      run: cat TestGCPMicroservice/.env

    - name: Print GCPMicroservice .env file
      run: cat GCPMicroservice/.env

    - name: Build the Docker image
      run: docker build --target publish -t gcpmicroservice .
