name: Docker Image CI
env:
  MIX_ENV: CD
  GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
  GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
        envkey_GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
        directory: GCPMicroservice
        file_name: .env
        fail_on_empty: true

    - name: Make envfile for test
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
        envkey_GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
        directory: TestGCPMicroservice
        file_name: .env
        fail_on_empty: true

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gcpmicroservice --target publish
