name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Export secrets as environment variables
      run: |
        echo "GCP_BUCKET=${{ secrets.GCP_BUCKET }}" >> $GITHUB_ENV
        echo "GCP_TOKEN=${{ secrets.GCP_TOKEN }}" >> $GITHUB_ENV

    - name: Create .env file
      run: | 
        mv $GITHUB_ENV .env
        cp .env ./TestGCPMicroservice/.env
        cp .env ./GCPMicroservice/.env

    - name: Build the Docker image
      run: docker build --target publish -t gcpmicroservice .
