@startuml DataObject_Create

legend top left
    Project
        BI_CSHARP_GCP

    Diagram
        DownloadObject sequence [DataObject]

    Authors
        Armand MARECHAL
        Mauro COSTA-DOS-SANTOS 
endlegend

actor User

participant "DataObject" as App
participant "GCP" as GCP

User -> App: DownloadObject
App -> GCP: DoesExist Request
GCP -> App: DoesExist Response

alt exist
    App -> GCP: GetObject Request
    GCP -> App: GetObject Response
    App -> User: Return Object
else
    App -> User: Throw Exception
end

@enduml